import fs from "node:fs";
import path from "node:path";
import type { DailyChallenge } from "../src/types";

const challengesDir = path.resolve(process.cwd(), "content/challenges");
const outputDir = path.resolve(process.cwd(), "worker/generated");
const outputFile = path.join(outputDir, "challenge-registry.ts");

function generateRegistry(): void {
  fs.mkdirSync(outputDir, { recursive: true });

  const challenges: Record<string, DailyChallenge> = {};

  const includeDrafts = process.env.INCLUDE_DRAFTS === "true" || process.argv.includes("--include-drafts");

  if (fs.existsSync(challengesDir)) {
    const files = fs.readdirSync(challengesDir).filter((f: string) => f.endsWith(".json"));

    for (const file of files) {
      const fullPath = path.join(challengesDir, file);
      try {
        const data = JSON.parse(fs.readFileSync(fullPath, "utf-8")) as DailyChallenge;
        // Invariant: Only Verified or Published challenges are registered for public serving,
        // unless in local development with INCLUDE_DRAFTS explicitly enabled
        if (
          data.editorialStatus === "Verified" ||
          data.editorialStatus === "Published" ||
          (includeDrafts && data.editorialStatus === "Draft")
        ) {
          challenges[data.cycleDate] = data;
        }
      } catch (err) {
        console.error(`Failed to read challenge ${file}:`, err);
      }
    }
  }

  // Generate TypeScript module
  const tsContent = `// AUTO-GENERATED BY scripts/generate-challenge-registry.ts - DO NOT EDIT MANUALLY
// Only challenges from content/challenges/ with editorialStatus 'Verified' or 'Published' are included.
// Test fixtures under tests/fixtures/ are strictly excluded.

import type { DailyChallenge } from "../../src/types";

export const CHALLENGE_REGISTRY: Record<string, DailyChallenge> = ${JSON.stringify(
    challenges,
    null,
    2
  )};

export function getChallengeByDate(cycleDate: string): DailyChallenge | undefined {
  return CHALLENGE_REGISTRY[cycleDate];
}

export function getAllRegisteredDates(): string[] {
  return Object.keys(CHALLENGE_REGISTRY).sort();
}
`;

  fs.writeFileSync(outputFile, tsContent, "utf-8");
  console.log(`Generated challenge registry at ${outputFile} with ${Object.keys(challenges).length} challenge(s).`);
}

generateRegistry();
